# Generated by Django 4.2.6 on 2023-10-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='iso_code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
