# Generated by Django 4.2.6 on 2023-10-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_language_iso_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='languages',
            field=models.ManyToManyField(help_text='Select a languages for this book', to='catalog.language'),
        ),
    ]
